import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'sairam',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: 'H&M',
        logo: '/images/logo1.png',
        description: 'best seller',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'chiru',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
    {
      name: 'gokul',
      email: 'gikul@example.com',
      password: bcrypt.hashSync('12345', 8),
      isAdmin: false,
      isSeller: true,
      seller: {
        name: 'Lee',
        logo: '/images/logo2.png',
        description: 'good seller',
        rating: 4.3,
        numReviews: 96,
      },
    },
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 1299,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 1199,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 1249,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 1499,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 1599,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 1399,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'nike set',
      category: 'Pants',
      image: '/images/p7.jpg',
      price: 1379,
      countInStock: 12,
      brand: 'nike',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'rabbit shirt',
      category: 'Shirts',
      image: '/images/p8.jpg',
      price: 749,
      countInStock: 12,
      brand: 'rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'zud shirt',
      category: 'Shirts',
      image: '/images/p9.jpg',
      price: 639,
      countInStock: 12,
      brand: 'zudio',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'zara shirt',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 895,
      countInStock: 12,
      brand: 'zara',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'puma pant',
      category: 'Pants',
      image: '/images/p11.jpg',
      price: 1799,
      countInStock: 12,
      brand: 'zara',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'zudio pant',
      category: 'Pants',
      image: '/images/p12.jpg',
      price: 799,
      countInStock: 12,
      brand: 'zudio',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'zudio shirt',
      category: 'Shirts',
      image: '/images/p13.jpg',
      price: 679,
      countInStock: 12,
      brand: 'zudio',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' shirt',
      category: 'Shirts',
      image: '/images/p14.jpg',
      price: 899,
      countInStock: 12,
      brand: 'zudio',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: '  raree shirt',
      category: 'Shirts',
      image: '/images/p15.jpg',
      price: 139,
      countInStock: 12,
      brand: 'zudio',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: '  H&M shirt',
      category: 'Shirts',
      image: '/images/p16.jpg',
      price: 1359,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: '  H&M shirts',
      category: 'Shirts',
      image: '/images/p17.jpg',
      price: 1399,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Adidas  Pant',
      category: 'Pants',
      image: '/images/p18.jpg',
      price: 1389,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'H&M  Pant',
      category: 'Pants',
      image: '/images/p19.jpg',
      price: 1439,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'H&M  blazer',
      category: 'blazers',
      image: '/images/p20.jpg',
      price: 1839,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Blueberry  blazer',
      category: 'blazers',
      image: '/images/p21.jpg',
      price: 5139,
      countInStock: 12,
      brand: 'Blueberry',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'park Avenue blazer',
      category: 'blazers',
      image: '/images/p22.jpg',
      price: 6139,
      countInStock: 12,
      brand: 'Park Avenue',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'x1 new watch',
      category: 'watch',
      image: '/images/p23.jpg',
      price: 1139,
      countInStock: 12,
      brand: 'x1 new',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'smart watch',
      category: 'watch',
      image: '/images/p24.jpg',
      price: 1239,
      countInStock: 12,
      brand: 'smart',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'puma shoes',
      category: 'Shoes',
      image: '/images/p25.jpg',
      price: 1349,
      countInStock: 12,
      brand: 'puma',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Gucci shoes',
      category: 'Shoes',
      image: '/images/p26.jpg',
      price: 1319,
      countInStock: 12,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Gucci xshoes',
      category: 'Shoes',
      image: '/images/p27.jpg',
      price: 1139,
      countInStock: 12,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'anime',
      category: 'Cosplay',
      image: '/images/p28.jpg',
      price: 1939,
      countInStock: 12,
      brand: 'anime',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'tanjiro',
      category: 'Cosplay',
      image: '/images/p29.jpg',
      price: 1839,
      countInStock: 12,
      brand: 'anime',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Rengoku',
      category: 'Cosplay',
      image: '/images/p30.jpg',
      price: 1739,
      countInStock: 12,
      brand: 'anime',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Naruto',
      category: 'Cosplay',
      image: '/images/p31.jpg',
      price: 2139,
      countInStock: 12,
      brand: 'Naruto',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Goku',
      category: 'Cosplay',
      image: '/images/p32.jpg',
      price: 1539,
      countInStock: 12,
      brand: 'Goku',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Eren',
      category: 'Cosplay',
      image: '/images/p33.jpg',
      price: 1739,
      countInStock: 12,
      brand: 'Eren',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Yuta',
      category: 'Action Figures',
      image: '/images/p34.jpg',
      price: 1939,
      countInStock: 12,
      brand: 'Anime',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Pancha',
      category: 'Ethic Wear',
      image: '/images/p35.jpg',
      price: 1139,
      countInStock: 12,
      brand: 'Ramraj',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Sherwani',
      category: 'Ethic Wear',
      image: '/images/p36.jpg',
      price: 7139,
      countInStock: 12,
      brand: 'Ramraj',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Kurta',
      category: 'Ethic Wear',
      image: '/images/p37.jpg',
      price: 6139,
      countInStock: 12,
      brand: 'Ramraj',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'T-Shirt blue',
      category: 'T-Shirt',
      image: '/images/p38.jpg',
      price: 4139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'T-Shirt purple',
      category: 'T-Shirt',
      image: '/images/p39.jpg',
      price: 2139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'T-Shirt black',
      category: 'T-Shirt',
      image: '/images/p40.jpg',
      price: 2139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Sweatshirt Peach',
      category: 'Sweatshirt',
      image: '/images/p41.jpg',
      price: 5139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Sweatshirt Olive',
      category: 'Sweatshirt',
      image: '/images/p42.jpg',
      price: 5139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Sweatshirt Blue',
      category: 'Sweatshirt',
      image: '/images/p43.jpg',
      price: 6139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Hoodie Black',
      category: 'Hoodies',
      image: '/images/p44.jpg',
      price: 3139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Hoodie Brown',
      category: 'Hoodies',
      image: '/images/p45.jpg',
      price: 3239,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Hoodie Blue',
      category: 'Hoodies',
      image: '/images/p46.jpg',
      price: 3139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Jackets 1',
      category: 'Jackets',
      image: '/images/p47.jpg',
      price: 4139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Jackets 2',
      category: 'Jackets',
      image: '/images/p48.jpg',
      price: 4539,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Jackets 3',
      category: 'Jackets',
      image: '/images/p49.jpg',
      price: 3639,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Shorts 1',
      category: 'Shorts',
      image: '/images/p50.jpg',
      price: 799,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Shorts 2',
      category: 'Shorts',
      image: '/images/p51.jpg',
      price: 699,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Shorts 3',
      category: 'Shorts',
      image: '/images/p52.jpg',
      price: 739,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Jeans 1',
      category: 'Jeans',
      image: '/images/p53.jpg',
      price: 1699,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Jeans 2',
      category: 'Jeans',
      image: '/images/p54.jpg',
      price: 2199,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Jeans 3',
      category: 'Jeans',
      image: '/images/p55.jpg',
      price: 1699,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Sleep Wear 1',
      category: 'Sleep Wear',
      image: '/images/p56.jpg',
      price: 1899,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Sleep Wear 2',
      category: 'Sleep Wear',
      image: '/images/p57.jpg',
      price: 1999,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Sleep Wear 3',
      category: 'Sleep Wear',
      image: '/images/p58.jpg',
      price: 1479,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Polo Shirts 1',
      category: 'Polo Shirts',
      image: '/images/p59.jpg',
      price: 2169,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Polo Shirts 2',
      category: 'Polo Shirts',
      image: '/images/p60.jpg',
      price: 139,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Polo Shirts 3',
      category: 'Polo Shirts',
      image: '/images/p61.jpg',
      price: 1879,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Polo Sweaters 1',
      category: 'Polo Sweaters ',
      image: '/images/p62.jpg',
      price: 1799,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Polo Sweaters 2',
      category: 'Polo Sweaters ',
      image: '/images/p63.jpg',
      price: 1979,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Polo Sweaters 3',
      category: 'Polo Sweaters ',
      image: '/images/p64.jpg',
      price: 1759,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Goggles 1',
      category: ' Goggles',
      image: '/images/p65.jpg',
      price: 599,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Goggles 2',
      category: ' Goggles',
      image: '/images/p66.jpg',
      price: 450,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Goggles 3',
      category: ' Goggles',
      image: '/images/p67.jpg',
      price: 579,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Half Shirt1',
      category: 'Half Shirt',
      image: '/images/p68.jpg',
      price: 599,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Half Shirt2',
      category: 'Half Shirt',
      image: '/images/p69.jpg',
      price: 499,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Half Shirt3',
      category: 'Half Shirt',
      image: '/images/p70.jpg',
      price: 670,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Over Sized T-Shirts 1',
      category: 'Over Sized T-Shirts',
      image: '/images/p71.jpg',
      price: 799,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Over Sized T-Shirts 2',
      category: 'Over Sized T-Shirts',
      image: '/images/p72.jpg',
      price: 849,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Over Sized T-Shirts 3',
      category: 'Over Sized T-Shirts',
      image: '/images/p73.jpg',
      price: 749,
      countInStock: 12,
      brand: 'H&M',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Winter Wear 1',
      category: 'Winter Wear',
      image: '/images/p74.jpg',
      price: 1599,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Winter Wear 2',
      category: 'Winter Wear',
      image: '/images/p75.jpg',
      price: 1799,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: 'Winter Wear 3',
      category: 'Winter Wear',
      image: '/images/p76.jpg',
      price: 1379,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Bandhgala 1',
      category: 'Bandhgala',
      image: '/images/p77.jpg',
      price: 2499,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Bandhgala 2',
      category: 'Bandhgala',
      image: '/images/p78.jpg',
      price: 2979,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Bandhgala 3',
      category: 'Bandhgala',
      image: '/images/p79.jpg',
      price: 2599,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Co-Ords 1',
      category: 'Co-Ords',
      image: '/images/p80.jpg',
      price: 1299,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Co-Ords 2',
      category: 'Co-Ords',
      image: '/images/p81.jpg',
      price: 1599,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Co-Ords 3',
      category: 'Co-Ords',
      image: '/images/p82.jpg',
      price: 1379,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Velvet Wear1',
      category: 'Velvet Wear',
      image: '/images/p83.jpg',
      price: 1299,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Velvet Wear2',
      category: 'Velvet Wear',
      image: '/images/p84.jpg',
      price: 1199,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Velvet Wear3',
      category: 'Velvet Wear',
      image: '/images/p85.jpg',
      price: 1279,
      countInStock: 12,
      brand: 'Rarre Rabbit',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Crocs1',
      category: 'Crocs',
      image: '/images/p86.jpg',
      price: 1999,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Crocs2',
      category: 'Crocs',
      image: '/images/p87.jpg',
      price: 2199,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Crocs3',
      category: 'Crocs',
      image: '/images/p88.jpg',
      price: 1799,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Slides 1',
      category: 'Slides',
      image: '/images/p89.jpg',
      price: 799,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Slides 2',
      category: 'Slides',
      image: '/images/p90.jpg',
      price: 879,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Slides 3',
      category: 'Slides',
      image: '/images/p91.jpg',
      price: 1299,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Sandles 3',
      category: 'Sandles',
      image: '/images/p92.jpg',
      price: 1999,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Sandles 2',
      category: 'Sandles',
      image: '/images/p93.jpg',
      price: 1399,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Sandles 1',
      category: 'Sandles',
      image: '/images/p94.jpg',
      price: 1439,
      countInStock: 12,
      brand: 'Crocs',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Corohet1',
      category: 'Corohet',
      image: '/images/p95.jpg',
      price: 1639,
      countInStock: 12,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Corohet2',
      category: 'Corohet',
      image: '/images/p96.jpg',
      price: 1639,
      countInStock: 12,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      name: ' Corohet3',
      category: 'Corohet',
      image: '/images/p97.jpg',
      price: 1639,
      countInStock: 12,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
